src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VideoRepository::class)
 */
class Video
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     */
    private $category;

    /**
     * @ORM\Column(type="integer")
     */
    private $category_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $youtube_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getYoutubeId(): ?string
    {
        return $this->youtube_id;
    }

    public function setYoutubeId(string $youtube_id): self
    {
        $this->youtube_id = $youtube_id;

        return $this;
    }

    public function getCategoryId(): ?string
    {
        return $this->category_id;
    }

    public function setCategoryId(int $category_id): self
    {
        $this->youtube_id = $category_id;

        return $this;
    }
}

src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Video;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('youtube_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

src/Controller/VideoController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Video;
use App\Form\VideoType;
use App\Services\Video\Interfaces\VideoServiceInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VideoController extends AbstractController
{
    /**
     * @Route("/show_videos", name="show_videos")
     */
    public function showVideos(VideoServiceInterface $videoService): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->render('video/show_videos.html.twig', [
            'videos' => $videoService->getAllVideos()
        ]);
    }

    /**
     * @Route("/show_video/{youtube_id}", name="show_video")
     */
    public function showVideo(string $youtube_id): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $video = $this->getDoctrine()
            ->getRepository(Video::class)
            ->findBy(['youtube_id' => $youtube_id]);

        return $this->render('video/show_video.html.twig', [
            'video' => $video[0]
        ]);
    }

    /**
     * @Route("/add_video", name="add_video")
     */
    public function addVideo(Request $request): Response
    {
        $video = new Video();
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($video);
            $entityManager->flush();

            return $this->redirectToRoute('show_videos', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('video/add_video.html.twig', [
            'video' => $video,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/show_video_by_cat/{category_id}", name="show_video_by_cat")
     */
    public function showByCategory(string $category_id, VideoServiceInterface $videoService): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->render('video/show_videos.html.twig', [
            'videos' => $videoService->getVideosByCategory($category_id)
        ]);
    }

    /**
     * @Route("/{id}", name="video_delete", methods={"POST"})
     */
    public function delete(Request $request, Video $video): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($video);
        $entityManager->flush();

        return $this->redirectToRoute('show_videos', [], Response::HTTP_SEE_OTHER);
    }
}

templates/video/_delete_form.html.twig
<form method="post" action="{{ path('video_delete', {'id': video.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video.id) }}">
    <button class="btn">Delete</button>
</form>

templates/video/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/video/add_video.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Video{% endblock %}

{% block main_cont %}
    <h1>Create new Video</h1>

    {{ include('video/_form.html.twig') }}

    <a href="{{ path('show_videos') }}">back to list</a>
{% endblock %}

templates/video/show_video.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VideoController!{% endblock %}

{% block main_cont %}
    <h1>{{ video.title }}</h1>
    <div class="grid">
        <div class="grid_item">
            <iframe width="600" height="300"
                    src="https://www.youtube.com/embed/{{ video.youtubeId }}"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
        </div>
    </div>

    {{ include('video/_delete_form.html.twig') }}
{% endblock %}

templates/video/show_videos.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VideoController!{% endblock %}

{% block main_cont %}
    <h1>My videos</h1>
    <div class="grid">
        {% for video in videos %}
            <div class="grid_item">
                <h4>
                    <a href="{{ path('show_video', {'youtube_id': video.youtubeId}) }}">
                        {{ video.title }}
                    </a>
                </h4> 
                <br>
                <iframe width="300" height="200"
                        src="https://www.youtube.com/embed/{{ video.youtubeId }}"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
            </div>
        {% endfor %}
    </div>
{% endblock %}